# Movies Data Set - Recommender
In this sample project, we create a recommender for movies. For this end, we take the [movies data set from kaggle](https://www.kaggle.com/rounakbanik/the-movies-dataset), explore the contents of these data, and finally create a recommender.<br>
We start with importing [Pandas](https://pandas.pydata.org/).

In [1]:
import pandas as pd

print( pd.__version__ )

0.24.2

Now, we find out, what files are available to us. For this end, we import __os__.

In [2]:
import os

In [3]:
path_to_movie_data = "C:\\Users\\rhopi\\OneDrive\\Desktop\\kaggle data 1\\movies data set\\"

movie_files = os.listdir( path_to_movie_data )

for f in movie_files:
    
    print( f )

credits.csv
keywords.csv
links.csv
links_small.csv
movies_metadata.csv
ratings.csv
ratings_small.csv

We will build a recommender that takes the keywords of a movie and an overview over the plot into account to make recommendations. We find the necessary data in __keywords.csv__ and __movies_metadata.csv__.<br>
Let's have a peek at __keywords.csv__:

In [4]:
keywords_data_raw = open( path_to_movie_data + "keywords.csv" )

i = 0

for line in keywords_data_raw:
    
    print( line )
    
    i = i + 1
    
    if i == 3:
        
        break

id,keywords

862,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290, 'name': 'toy'}, {'id': 5202, 'name': 'boy'}, {'id': 6054, 'name': 'friendship'}, {'id': 9713, 'name': 'friends'}, {'id': 9823, 'name': 'rivalry'}, {'id': 165503, 'name': 'boy next door'}, {'id': 170722, 'name': 'new toy'}, {'id': 187065, 'name': 'toy comes to life'}]"

8844,"[{'id': 10090, 'name': 'board game'}, {'id': 10941, 'name': 'disappearance'}, {'id': 15101, 'name': ""based on children's book""}, {'id': 33467, 'name': 'new home'}, {'id': 158086, 'name': 'recluse'}, {'id': 158091, 'name': 'giant insect'}]"

Now, we read __keywords.csv__ into a Pandas dataframe.

In [5]:
keywords_df = pd.read_csv( path_to_movie_data + "keywords.csv" )

keywords_df.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

Next, we repeat those steps for __movies_metadata.csv__.

In [6]:
meta_data_raw = open( path_to_movie_data + "movies_metadata.csv" )

i = 0

for line in meta_data_raw:
    
    print( line )
    
    i = i + 1
    
    if i == 3:
        
        break

adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count

False,"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,Toy Story,False,7.7,5415

False,,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]",,8844,tt0113497,en,Jumanji,"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.",17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'name': 'Teitler Film', 'id': 2550}, {'name': 'Interscope Communications', 'id': 10201}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'fr', 'name': 'FranÃ§ais'}]",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413

In [7]:
metadata_df = pd.read_csv( path_to_movie_data + "movies_metadata.csv" )

metadata_df.head()

C:\Users\rhopi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

Next, we combine both dataframes to a custom dataframe.<br>
For this, we match both dataframes by the __id__, and then we insert into the new dataframe the keywords from __keywords_df__ and the __original_title__, the __overview__ and the __vote_average__.

In [8]:
def get_metadata_by_id( movie_id ):
    
    """ 
        This function takes the id as input parameter and then selects that entry in metadata_df
        which has the same movie_id. Then the data from the columns "original_title", "overview" and
        "vote_average" are extracted, put into a list, and this list is returned.
        If the movie_id cannot be found, -1 is returned.
    """
    
    df = metadata_df.loc[ metadata_df[ "id" ] == movie_id ]
    
    if df.empty:
        
        return -1
    
    
    
    overview_text = df[ "overview" ].values[ 0 ]
    
    
    
    
    if overview_text != overview_text:
        
        return -1
    
    
    
    overview_text = overview_text.lower()
    
    overview_text = overview_text.replace( ".", "" )
    
    overview_text = overview_text.replace( ",", "" )
    
    overview_text = overview_text.replace( ";", "" )
    
    overview_text = overview_text.replace( "?", "" )
    
    overview_text = overview_text.replace( "!", "" )
    
    overview_text = overview_text.replace( "-", "" )
    
    
    
    
    
    bag_of_words = overview_text.split( " " )
    
    new_bag_of_words = []
    
    for item in bag_of_words:
        
        if len( item ) > 0:
            
            if item not in new_bag_of_words:
                
                new_bag_of_words.append( item )
                
                
                
    
    data = [ df[ "original_title" ].values[ 0 ], new_bag_of_words, df[ "vote_average" ].values[ 0 ] ]
    
    return data

In [9]:
def extract_keywords_by_index( index ):
    
    """
        This function first checks, whether the index is valid. If not -1 is returned.
        If the index is valid, the raw keywords string is extracted.
        We then manipulate this string until a list of keywords is achieved. If this list is
        empty, we return -1, else, we return the list.
    """
    
    if index < 0:
        
        return -1
    
    if index >= len( keywords_df ):
        
        return -1
    
    
    
    raw_string = keywords_df.iloc[ index ][ "keywords" ]
    
    raw_string = raw_string[ 1 : len( raw_string ) - 1 ]
    
    list_of_substrings = raw_string.replace( "{", "}" ).split( "}" )
    
    list_of_substrings = list_of_substrings[ 1 : len( list_of_substrings ) - 1 ]
    
    
    
    
    new_list_of_substrings = []
    
    for item in list_of_substrings:
        
        if "name" in item:
            
            new_list_of_substrings.append( item )
            
            
            
            
    another_list_of_substrings = []
    
    for item in new_list_of_substrings:
        
        another_list_of_substrings.append( item.split( "name" )[ 1 ] )
        
        
        
        
    yet_another_list_of_substrings = []
    
    for item in another_list_of_substrings:
        
        yet_another_list_of_substrings.append( item[ 4 : len( item ) - 1 ] )
        
        
        
        
    final_list_of_substrings = []
    
    for item in yet_another_list_of_substrings:
        
        if len( item ) > 0:
            
            final_list_of_substrings.append( item )
            
            
            
            
    if len( final_list_of_substrings ) == 0:
        
        return -1
         
    return final_list_of_substrings

In [10]:
data = []




for i in range( len( keywords_df ) ):
    
    movie_id = str( keywords_df.loc[ i ][ "id" ] )
    
    keywords = extract_keywords_by_index( i )
    
    metadata = get_metadata_by_id( movie_id )
    
    
    
    if keywords == -1:
        
        continue
        
    insert = []
    
    if metadata == -1:
        
        continue
        
    for item in metadata:
        
        insert.append( item )
        

    
    insert.append( keywords )
    
    data.append( insert )
    
    
    
    
combined_data = pd.DataFrame( data, columns = [ "Title", "Overview", "Rating", "Keywords" ] )

combined_data.head()

,Title,Overview,Rating,Keywords
0,Toy Story,"[led, by, woody, andy's, toys, live, happily, ...",7.7,"[jealousy, toy, boy, friendship, friends, riva..."
1,Jumanji,"[when, siblings, judy, and, peter, discover, a...",6.9,"[board game, disappearance, based on children'..."
2,Grumpier Old Men,"[a, family, wedding, reignites, the, ancient, ...",6.5,"[fishing, best friend, duringcreditsstinger, o..."
3,Waiting to Exhale,"[cheated, on, mistreated, and, stepped, the, w...",6.1,"[based on novel, interracial relationship, sin..."
4,Father of the Bride Part II,"[just, when, george, banks, has, recovered, fr...",5.7,"[baby, midlife crisis, confidence, aging, daug..."

Next, we want to compute the tf-idf-score for the words in the Overview and the Keywords.<br>
The tf-idf-score is computed as the product of the tf-score and and the idf-score.<br>
The tf-score is computed as follows: 
$$tf\left( w, D\right)=\frac{\# w \text{ in D}}{\text{max}_{w^{*} \text{ in D}}\#w^{*}}$$ 
for a given word w.<br>
The idf-score is computed as follows:
$$idf\left( w \right) = \log \left( \frac{N}{\sum_{D}1_{w\text{ in D}}}\right)$$
Here, $N$ is the number of documents, and $1_{w\text{ in D}}$ is the function that returns $1$ if $w$ is in $D$ and $0$ otherwise.<br>
In our case, each word appears only once, therefore, we only consider the idf-score.<br>
Next, we create for the Overview and the Keywords dictionaries in order to count how often each word appears.

In [11]:
overview_word_counter = {}

keywords_word_counter = {}



for i in range( len( combined_data ) ):
    
    overview_words = combined_data.loc[ i ][ "Overview" ]
    
    for word in overview_words:
        
        if word not in overview_word_counter:
            
            overview_word_counter[ word ] = 1
            
        else:
            
            overview_word_counter[ word ] = overview_word_counter[ word ] + 1
            
            
            
    keywords_words = combined_data.loc[ i ][ "Keywords" ]
    
    for word in keywords_words:
        
        if word not in keywords_word_counter:
            
            keywords_word_counter[ word ] = 1
            
        else:
            
            keywords_word_counter[ word ] = keywords_word_counter[ word ] + 1

Now, we create the actual recommender.<br>
We give this function the name of a movie, and compare for all the other movies, which words from the overview and the keywords they have in common. Then, we sum over the idf-scores of these words, and finally, we multiply this sum with the rating of the other movie.

In [12]:
import numpy as np

print( np.__version__ )

1.16.2

In [13]:
def recommender( movie ):
    """
        First, check, whether movie appears in the data set.
        Then extract the overview and the keywords of that movie.
        Then we iterate overall the other movies. We extract their overviews and keywords, 
        and check, which of these words are in common with the words that describe movie.
        Then we sum the idf-scores of these words and multiply the result by the rating.
    """
    
    found = False
    
    j = -1
    
    N = len( combined_data )
    
    
    
    
    for i in range( N ):
        
        if movie == combined_data.loc[ i ][ "Title" ]:
            
            found = True
            
            j = i
            
            break
            
    if not found:
        
        return -1
    
    
    
    
    original_overview = combined_data.loc[ i ][ "Overview" ]
    
    original_keywords = combined_data.loc[ i ][ "Keywords" ]
    
    data = []
    
    
    
    
    for i in range( N ):
        
        if i != j:
            
            new_overview = combined_data.loc[ i ][ "Overview" ]
            
            new_keywords = combined_data.loc[ i ][ "Keywords" ]
            
            
            
            
            common_overview = []
            
            common_keywords = []
            
            
            
            
            
            for word in original_overview:
                
                if word in new_overview:
                    
                    common_overview.append( word )
                    
                    
                    
                    
                    
            for word in original_keywords:
                
                if word in new_keywords:
                    
                    common_keywords.append( word )
                    
                    
                    
                    
            
            weight = 0.0
            
            fN = np.float( N )
            
            
            
            
            
            for word in common_overview:
                
                weight = weight + np.log( fN / np.float( overview_word_counter[ word ] ) )
                
            for word in common_keywords:
                
                weight = weight + np.log( fN / np.float( keywords_word_counter[ word ] ) )  
                
                
                
                
                
            weight = weight * combined_data.loc[ i ][ "Rating" ]
            
            
            
            
            if weight > 0:
            
                insert = [ combined_data.loc[ i ][ "Title" ], weight ]
            
                data.append( insert )
            
            
            
            
            
            
    result_df = pd.DataFrame( data, columns = [ "Title", "Weight" ] )
    
    result_df = result_df.sort_values( by = "Weight", axis = 0, ascending = False )
    
    result_df = result_df.reset_index( drop = True )
    
    
    

    
    suggestions = []
    
    for i in range( min( 10, len( result_df ) ) ):
        
        suggestions.append( result_df.loc[ i ][ "Title" ] )
        
    for item in suggestions:
        
        print( item )

In [14]:
recommender( "Toy Story" )

Toy Story 2
Toy Story 3
The Tangerine Bear: Home in Time for Christmas!
Bride for Rent
Bride for Rent
Samotáři
Django Unchained
Steal a Pencil for Me
Pinocchio
Werckmeister harmóniák

In [15]:
recommender( "Leaving Las Vegas" )

8½
Dead Man Walking
Airplane!
Monsieur Ibrahim et les fleurs du Coran
Once Were Warriors
The Good Heart
Barton Fink
La strada
Un baiser s'il vous plaît
Le Mépris

In [16]:
recommender( "Casino" )

Drugstore Cowboy
Bugsy
Elvis That's the Way It Is
Lucky You
To Be the Best
Dave Attell's Insomniac Tour: Uncensored!
The Legend of Jimmy the Greek
Next
Heldorado
Alien: Covenant

In [17]:
recommender( "GoldenEye" )

The Living Daylights
You Only Live Twice
Dr. No
From Russia with Love
Live and Let Die
The Spy Who Loved Me
The Dark Knight Rises
For Your Eyes Only
Tomorrow Never Dies
Octopussy

In [18]:
recommender( "Othello" )

Ben-Hur
Jedi Junior High
Othello
Othello
Fuse: Memoirs of the Hunter Girl
Fuse: Memoirs of the Hunter Girl
O
Hamlet
To Catch a Thief
Gladiator

In [19]:
recommender( "Nixon" )

Frost/Nixon
Our Nixon
Dick
명왕성
Into the Woods
Primary Colors
Wag the Dog
Hawking
Black Mirror: White Christmas
The Sheik